# настройки которые мы подключаем через include во все конфиги, чтобы не дублировать во все
geo $remote_addr $trusted_proxy {
    default      0;
    172.20.0.20  1; 
    172.20.0.11  1; 
    172.20.0.12  1; 
    172.20.0.13  1;
}

map $trusted_proxy $xff_value {
    1  "$http_x_forwarded_for, $remote_addr";
    0  $remote_addr;
}
