#условный балансировщик, чтобы рандомно обращался на какой то из nginx
user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include  /etc/nginx/mime.types;

    upstream nginx_pool {
        server nginx1:80;
        server nginx2:80;
        server nginx3:80;
    }

    server {
        listen 80;

        location /healthz {
            access_log off;
            return 200 "ok\n";
        }

        location / {
            proxy_set_header X-Forwarded-For  $remote_addr;
            proxy_set_header X-Real-IP        $remote_addr;
            proxy_set_header Host             $host;
            proxy_pass http://nginx_pool;
        }
    }
}
